/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_usbuart_api_UsbUartContext */

#ifndef _Included_info_usbuart_api_UsbUartContext
#define _Included_info_usbuart_api_UsbUartContext
#ifdef __cplusplus
extern "C" {
#endif
#undef info_usbuart_api_UsbUartContext_DEFAULT_LOOP_TIMEOUT
#define info_usbuart_api_UsbUartContext_DEFAULT_LOOP_TIMEOUT 500L
/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_info_usbuart_api_UsbUartContext_create
  (JNIEnv *, jclass);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    loop
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_info_usbuart_api_UsbUartContext_loop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    attach
 * Signature: (JIILinfo/usbuart/api/UsbUartContext/ChannelPriv;Linfo/usbuart/api/EIA_TIA_232_Info;)I
 */
JNIEXPORT jint JNICALL Java_info_usbuart_api_UsbUartContext_attach
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jobject);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    pipe
 * Signature: (JIILinfo/usbuart/api/UsbUartContext/ChannelPriv;Linfo/usbuart/api/EIA_TIA_232_Info;)I
 */
JNIEXPORT jint JNICALL Java_info_usbuart_api_UsbUartContext_pipe
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jobject);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    sendbreak
 * Signature: (JLinfo/usbuart/api/UsbUartContext/ChannelPriv;)I
 */
JNIEXPORT jint JNICALL Java_info_usbuart_api_UsbUartContext_sendbreak
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    status
 * Signature: (JLinfo/usbuart/api/UsbUartContext/ChannelPriv;)I
 */
JNIEXPORT jint JNICALL Java_info_usbuart_api_UsbUartContext_status
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    reset
 * Signature: (JLinfo/usbuart/api/UsbUartContext/ChannelPriv;)I
 */
JNIEXPORT jint JNICALL Java_info_usbuart_api_UsbUartContext_reset
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    close
 * Signature: (JLinfo/usbuart/api/UsbUartContext/ChannelPriv;)V
 */
JNIEXPORT void JNICALL Java_info_usbuart_api_UsbUartContext_close
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     info_usbuart_api_UsbUartContext
 * Method:    hotplug
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_info_usbuart_api_UsbUartContext_hotplug
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
